package View_Controller;

import Model.Contact;
import Model.Customer;
import Model.User;
import javafx.event.ActionEvent;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

import static DBAccess.DBContact.getAllContacts;
import static DBAccess.DBCustomer.getAllCustomers;
import static DBAccess.DBUser.getAllUsers;

/** This class enables user to add new appointment. Users fill out a form with text fields for
 * title of the appointment, description, type and location. New Appointment ID is auto generated in the Appt ID
 * text field and is disabled. There are also combo boxes for Customer ID, User ID and Contact to be assigned
 * to the appointment. This enables user to choose from pre-existing list of choices. There is also a date picker
 * for user to select date of appointment, and spinner boxes for user to select start and end time for appointment.*/
public class AddAppointmentController implements Initializable {

    public TextField addApptIDText;
    public TextField addApptTitleText;
    public TextField addApptDescriptionText;
    public TextField addApptLocationText;
    public ComboBox addApptContactCombo;
    public ComboBox addApptCustomerIDCombo;
    public ComboBox addApptUserIDCombo;
    public DatePicker addApptDatePicker;
    public TextField addApptTypeText;
    public ComboBox addApptStartTimeCombo;
    public ComboBox addApptEndTimeCombo;

    Stage stage;
    Parent scene;

    /** This method initializes add appointment screen combo boxes with a list of selection.
     * @param url the location
     * @param resourceBundle the resources.*/
    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {

        //Displays all customers in Combo Box:
        addApptCustomerIDCombo.setItems(getAllCustomers());
        //Displays all users in Combo Box:
        addApptUserIDCombo.setItems(getAllUsers());
        //Displays all contacts in Combo Box:
        addApptContactCombo.setItems(getAllContacts());

    }

    /** This method allows user to cancel adding an appointment.
     * Cancel button switches user back to previous screen: Appointment Table View list.
     * @param actionEvent the event or mouse click on Cancel button.*/
    public void onActionAddApptCancelBtn(ActionEvent actionEvent) throws IOException {

        stage = (Stage) ((Button)actionEvent.getSource()).getScene().getWindow();
        scene = FXMLLoader.load(getClass().getResource("/View_Controller/ApptTableView.fxml"));
        stage.setScene(new Scene(scene));
        stage.show();

    }

    /** This method enables user to add new appointment to database.
     * This also switches user back to previous screen: Appointment Table View list.
     * @param actionEvent the event or mouse click on Add button.*/
    public void onActionAddApptBtn(ActionEvent actionEvent) throws IOException {

        Customer customer = (Customer) addApptCustomerIDCombo.getSelectionModel().getSelectedItem();
        //Obtain int customerId based on combo box selection:
        int customerIdCombo = customer.getCustomerId();
        System.out.println("customerID " + customerIdCombo);

        User user = (User) addApptUserIDCombo.getSelectionModel().getSelectedItem();
        //Obtain int userId based on combo box selection:
        int userIdCombo = user.getUserId();
        System.out.println("userID " + userIdCombo);

        int apptId; //auto generated by database

        String type = addApptTypeText.getText();
        String title = addApptTitleText.getText();
        String desc = addApptDescriptionText.getText();
        String location = addApptLocationText.getText();

        Contact contact = (Contact) addApptContactCombo.getSelectionModel().getSelectedItem();
        //Obtain String contact name based on combo box selection:
        String contactCombo = contact.getContactName();
        System.out.println("contact Name: " + contactCombo);

        //Grab date selected by user from date picker:
        LocalDate datePicker = addApptDatePicker.getValue();
        System.out.println("date: " + datePicker);

        LocalTime startCombo;
        LocalTime endCombo;

        //Check local time now/TESTING (working):
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime now = LocalTime.now();
        System.out.println("Current local time " + dtf.format(now)); //Formats localtime to HH:mm --> format dtf.format()
        //TODO:Delete above code snippet later.

        stage = (Stage) ((Button)actionEvent.getSource()).getScene().getWindow();
        scene = FXMLLoader.load(getClass().getResource("/View_Controller/ApptTableView.fxml"));
        stage.setScene(new Scene(scene));
        stage.show();

    }

}
